version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esgis-chatbot
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - IS_LAMBDA_ENVIRONMENT=false
      - USE_MEMORY_ADAPTER=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=${API_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
