AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation Template for the Application

###############################################################################
Parameters:
###############################################################################
  EnvironmentName:
    Description: Environment name for the application dev/staging/production
    Type: String
    AllowedValues:
      - tleguede
      - dev
      - preprod
      - prod
      - tleguede-dev
      - tleguede-preprod
      - tleguede-prod
  
  TelegramBotToken:
    Description: Token for the Telegram bot
    Type: String
    NoEcho: true
  
  MistralApiKey:
    Description: API key for Mistral AI
    Type: String
    NoEcho: true

###############################################################################
Resources:
###############################################################################
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "chatbot-dbtable-v2-${EnvironmentName}"
      # Ancien nom: chatbot-dbtable-${EnvironmentName}
      # Supprimer cette ligne de commentaire après la migration
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Définir d'abord la fonction Lambda
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chatbot-lambda-${EnvironmentName}"
      CodeUri: ../
      Handler: src/lambda.lambda_handler
      Runtime: python3.9
      # Augmenter le timeout et la mémoire pour éviter les timeouts
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          MISTRAL_API_KEY: !Ref MistralApiKey
          DATABASE_TYPE: "dynamodb"
          DYNAMO_TABLE: !Ref DynamoDBTable
          ENV: !Ref EnvironmentName
          # URL de l'API construite dynamiquement
          API_URL: !Sub 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
      # Pas d'intégration directe avec API Gateway pour éviter les dépendances circulaires
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:DeleteItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:Query'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:BatchWriteItem'
                - 'dynamodb:BatchGetItem'
                - 'dynamodb:DescribeTable'
                - 'dynamodb:ConditionCheckItem'
              Resource: !GetAtt DynamoDBTable.Arn
            - Effect: Allow
              Action:
                - 'dynamodb:Query'
              Resource: !Sub '${DynamoDBTable.Arn}/index/*'

  # API Gateway HTTP API
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "chatbot-apigateway-${EnvironmentName}"
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
      
  # Stage pour l'API Gateway
  ApiGatewayDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref Api
      StageName: $default
      AutoDeploy: true
      
  # Intégration Lambda avec API Gateway
  ApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Api
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt Function.Arn
      PayloadFormatVersion: '2.0'
      
  # Route par défaut pour l'API Gateway
  ApiDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: '$default'
      Target: !Join
        - /
        - - integrations
          - !Ref ApiIntegration
          
  # Permission pour que l'API Gateway puisse appeler la fonction Lambda
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Function
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref Api
          - '/*/*'

Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
    Description: Name of the DynamoDB table
  ApiUrl:
    Description: URL of your API
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
